/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlankRouteRouteImport } from './routes/_blank/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as Errors500RouteImport } from './routes/errors/500'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as Errors403RouteImport } from './routes/errors/403'
import { Route as AuthenticatedCoreRouteRouteImport } from './routes/_authenticated/_core/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/_dashboard/index'
import { Route as BlankAuthLoginRouteImport } from './routes/_blank/_auth/login'
import { Route as AuthenticatedExampleTableV2DemoRouteImport } from './routes/_authenticated/example/table-v2-demo'
import { Route as AuthenticatedCoreUsersRouteImport } from './routes/_authenticated/_core/users'
import { Route as AuthenticatedCoreProfileRouteImport } from './routes/_authenticated/_core/profile'
import { Route as AuthenticatedCoreFileManagementRouteImport } from './routes/_authenticated/_core/file-management'

const BlankRouteRoute = BlankRouteRouteImport.update({
  id: '/_blank',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoreRouteRoute = AuthenticatedCoreRouteRouteImport.update({
  id: '/_core',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/_dashboard/',
    path: '/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlankAuthLoginRoute = BlankAuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => BlankRouteRoute,
} as any)
const AuthenticatedExampleTableV2DemoRoute =
  AuthenticatedExampleTableV2DemoRouteImport.update({
    id: '/example/table-v2-demo',
    path: '/example/table-v2-demo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoreUsersRoute = AuthenticatedCoreUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedCoreRouteRoute,
} as any)
const AuthenticatedCoreProfileRoute =
  AuthenticatedCoreProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCoreRouteRoute,
  } as any)
const AuthenticatedCoreFileManagementRoute =
  AuthenticatedCoreFileManagementRouteImport.update({
    id: '/file-management',
    path: '/file-management',
    getParentRoute: () => AuthenticatedCoreRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/file-management': typeof AuthenticatedCoreFileManagementRoute
  '/profile': typeof AuthenticatedCoreProfileRoute
  '/users': typeof AuthenticatedCoreUsersRoute
  '/example/table-v2-demo': typeof AuthenticatedExampleTableV2DemoRoute
  '/login': typeof BlankAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/file-management': typeof AuthenticatedCoreFileManagementRoute
  '/profile': typeof AuthenticatedCoreProfileRoute
  '/users': typeof AuthenticatedCoreUsersRoute
  '/example/table-v2-demo': typeof AuthenticatedExampleTableV2DemoRoute
  '/login': typeof BlankAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_blank': typeof BlankRouteRouteWithChildren
  '/_authenticated/_core': typeof AuthenticatedCoreRouteRouteWithChildren
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/_authenticated/_core/file-management': typeof AuthenticatedCoreFileManagementRoute
  '/_authenticated/_core/profile': typeof AuthenticatedCoreProfileRoute
  '/_authenticated/_core/users': typeof AuthenticatedCoreUsersRoute
  '/_authenticated/example/table-v2-demo': typeof AuthenticatedExampleTableV2DemoRoute
  '/_blank/_auth/login': typeof BlankAuthLoginRoute
  '/_authenticated/_dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/file-management'
    | '/profile'
    | '/users'
    | '/example/table-v2-demo'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/file-management'
    | '/profile'
    | '/users'
    | '/example/table-v2-demo'
    | '/login'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_blank'
    | '/_authenticated/_core'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/_authenticated/_core/file-management'
    | '/_authenticated/_core/profile'
    | '/_authenticated/_core/users'
    | '/_authenticated/example/table-v2-demo'
    | '/_blank/_auth/login'
    | '/_authenticated/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BlankRouteRoute: typeof BlankRouteRouteWithChildren
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_blank': {
      id: '/_blank'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BlankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_core': {
      id: '/_authenticated/_core'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCoreRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_dashboard/': {
      id: '/_authenticated/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_blank/_auth/login': {
      id: '/_blank/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof BlankAuthLoginRouteImport
      parentRoute: typeof BlankRouteRoute
    }
    '/_authenticated/example/table-v2-demo': {
      id: '/_authenticated/example/table-v2-demo'
      path: '/example/table-v2-demo'
      fullPath: '/example/table-v2-demo'
      preLoaderRoute: typeof AuthenticatedExampleTableV2DemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_core/users': {
      id: '/_authenticated/_core/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedCoreUsersRouteImport
      parentRoute: typeof AuthenticatedCoreRouteRoute
    }
    '/_authenticated/_core/profile': {
      id: '/_authenticated/_core/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedCoreProfileRouteImport
      parentRoute: typeof AuthenticatedCoreRouteRoute
    }
    '/_authenticated/_core/file-management': {
      id: '/_authenticated/_core/file-management'
      path: '/file-management'
      fullPath: '/file-management'
      preLoaderRoute: typeof AuthenticatedCoreFileManagementRouteImport
      parentRoute: typeof AuthenticatedCoreRouteRoute
    }
  }
}

interface AuthenticatedCoreRouteRouteChildren {
  AuthenticatedCoreFileManagementRoute: typeof AuthenticatedCoreFileManagementRoute
  AuthenticatedCoreProfileRoute: typeof AuthenticatedCoreProfileRoute
  AuthenticatedCoreUsersRoute: typeof AuthenticatedCoreUsersRoute
}

const AuthenticatedCoreRouteRouteChildren: AuthenticatedCoreRouteRouteChildren =
  {
    AuthenticatedCoreFileManagementRoute: AuthenticatedCoreFileManagementRoute,
    AuthenticatedCoreProfileRoute: AuthenticatedCoreProfileRoute,
    AuthenticatedCoreUsersRoute: AuthenticatedCoreUsersRoute,
  }

const AuthenticatedCoreRouteRouteWithChildren =
  AuthenticatedCoreRouteRoute._addFileChildren(
    AuthenticatedCoreRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoreRouteRoute: typeof AuthenticatedCoreRouteRouteWithChildren
  AuthenticatedExampleTableV2DemoRoute: typeof AuthenticatedExampleTableV2DemoRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoreRouteRoute: AuthenticatedCoreRouteRouteWithChildren,
  AuthenticatedExampleTableV2DemoRoute: AuthenticatedExampleTableV2DemoRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlankRouteRouteChildren {
  BlankAuthLoginRoute: typeof BlankAuthLoginRoute
}

const BlankRouteRouteChildren: BlankRouteRouteChildren = {
  BlankAuthLoginRoute: BlankAuthLoginRoute,
}

const BlankRouteRouteWithChildren = BlankRouteRoute._addFileChildren(
  BlankRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BlankRouteRoute: BlankRouteRouteWithChildren,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
