/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlankRouteImport } from './routes/_blank'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as Errors500RouteImport } from './routes/errors/500'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as Errors403RouteImport } from './routes/errors/403'
import { Route as BlankLoginRouteImport } from './routes/_blank.login'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'

const BlankRoute = BlankRouteImport.update({
  id: '/_blank',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankLoginRoute = BlankLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BlankRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/users': typeof AuthenticatedUsersRoute
  '/login': typeof BlankLoginRoute
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/users': typeof AuthenticatedUsersRoute
  '/login': typeof BlankLoginRoute
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_blank': typeof BlankRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_blank/login': typeof BlankLoginRoute
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/users'
    | '/login'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users' | '/login' | '/errors/403' | '/errors/404' | '/errors/500'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_blank'
    | '/_authenticated/users'
    | '/_blank/login'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlankRoute: typeof BlankRouteWithChildren
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_blank': {
      id: '/_blank'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blank/login': {
      id: '/_blank/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof BlankLoginRouteImport
      parentRoute: typeof BlankRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlankRouteChildren {
  BlankLoginRoute: typeof BlankLoginRoute
}

const BlankRouteChildren: BlankRouteChildren = {
  BlankLoginRoute: BlankLoginRoute,
}

const BlankRouteWithChildren = BlankRoute._addFileChildren(BlankRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlankRoute: BlankRouteWithChildren,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
